# github.com/go-task/task

version: '2'

vars:
  COVERAGE_DIR: "<%= coverageReportDirectory %>"
  COVOUT_FILE: "{{.COVERAGE_DIR}}/coverage.out"
  GOCOV_JSON_FILE: "{{.COVERAGE_DIR}}/gocov.json"
  GOCOV_HTML_FILE: "{{.COVERAGE_DIR}}/index.html"
  COBERTURA_XML_FILE: "{{.COVERAGE_DIR}}/cobertura.xml"
  TESTRESULTS_DIR: "<%= testResultsReportDirectory %>"
  JUNIT_RESULTS_FILE: "{{.TESTRESULTS_DIR}}/junit.xml"
  JSON_RESULTS_FILE: "{{.TESTRESULTS_DIR}}/unit.json"

tasks:
  default:
    deps: [<%= taskRunnerConfig.taskScriptNames.test %>]
    silent: true

  <%= taskRunnerConfig.taskScriptNames.setup %>:
    desc: Sets up the workspace.
    deps: [<%= taskRunnerConfig.taskScriptNames.install %>, create-report-dirs]
    # cmds:
    #   - go install .
    #   - captain-githook init

  <%= taskRunnerConfig.taskScriptNames.install %>:
    desc: Installs dependencies
    deps: [install-deps, install-dev-deps]
    silent: true

  install-deps:
    desc: Runs go mod download
    cmds:
      - go mod download
    silent: true

  install-dev-deps:
    desc: Installs dev dependencies.
    # Run this outside the working directory to prevent
    # these dev deps from being added to the go.mod file.
    dir: '{{toSlash .TMP_DIR}}'
    cmds:
      - go get github.com/axw/gocov/gocov
      - go get github.com/AlekSi/gocov-xml
      - go get github.com/matm/gocov-html
      - go get gotest.tools/gotestsum
      - go get <%= linterConfig.packageInstallPath %>
    silent: true
    vars:
      TMP_DIR:
        sh: go env GOPATH

  create-report-dirs:
    desc: Creates the directories where generated reports are written.
    cmds:
      - '{{if eq OS "windows"}}cmd.exe /C IF NOT EXIST {{.TESTRESULTS_DIR}} mkdir{{else}}mkdir -p{{end}} {{.TESTRESULTS_DIR}}'
      - '{{if eq OS "windows"}}cmd.exe /C IF NOT EXIST {{.COVERAGE_DIR}} mkdir{{else}}mkdir -p{{end}} {{.COVERAGE_DIR}}'
    silent: true

  <%= taskRunnerConfig.taskScriptNames.clean %>:
    desc: Cleans the workspace.
    cmds:
      - '{{if eq OS "windows"}}cmd.exe /C rd /Q /S{{else}}rm -rf{{end}} {{.TESTRESULTS_DIR}} {{.COVERAGE_DIR}}'
    silent: true
    ignore_error: true

  <%= taskRunnerConfig.taskScriptNames.test %>:
    desc: Runs unit tests.
    deps: [create-report-dirs]
    cmds:
      - gotestsum --format standard-verbose --junitfile {{.JUNIT_RESULTS_FILE}} --jsonfile {{.JSON_RESULTS_FILE}} -- -coverprofile={{.COVOUT_FILE}} <%= goContentConfig.testTarget %>
    silent: true

  <%= taskRunnerConfig.taskScriptNames.coverage %>:
    desc: Runs unit tests and generates code coverage reports.
    deps: [<%= taskRunnerConfig.taskScriptNames.test %>]
    cmds:
      - gocov convert {{.COVOUT_FILE}} > {{.GOCOV_JSON_FILE}}
      - gocov-xml < {{.GOCOV_JSON_FILE}} > {{.COBERTURA_XML_FILE}}
      - gocov-html {{.GOCOV_JSON_FILE}} > {{.GOCOV_HTML_FILE}}
    silent: true

  <%= taskRunnerConfig.taskScriptNames.openCoverage %>:
    desc: Opens the HTML Code Coverage Report
    deps: [<%= taskRunnerConfig.taskScriptNames.coverage %>]
    cmds:
      - '{{if eq OS "windows"}}cmd.exe /C start{{else if eq OS "darwin"}}open{{else}}xdg-open{{end}} {{.GOCOV_HTML_FILE}}'

  <%= taskRunnerConfig.taskScriptNames.lint %>:
    desc: Runs the linter and prints results to STDOUT.
    cmds:
      - <%= linterConfig.commandName %> ./...

  <%= taskRunnerConfig.taskScriptNames.vet %>:
    desc: Runs govet and prints results to STDOUT.
    cmds:
      - go vet ./...

  <%= taskRunnerConfig.taskScriptNames.ci %>:
    desc: Runs sequence of desired commands for performing validation in a CI build
    deps: [<%= taskRunnerConfig.taskScriptNames.coverage %>, <%= taskRunnerConfig.taskScriptNames.lint %>]

  print-version:
    desc: Prints the current captain-githook package version
    cmds:
      - go run ./scripts/version/print/main.go
    silent: true

  bump-version:
    desc: Bumps the current captain-githook package patch version
    cmds:
      - go run ./scripts/version/bump/main.go
    silent: true