name: linux-ci
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.impactful }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            impactful:
              - .github/workflows/linux.yml
              - generators/**/*
              - test/**/*
              - .eslint*
              - package*.json
              - ts*.json

  build:
    runs-on: ubuntu-latest
    needs: detect-changes
    name: linux-node-v${{ matrix.node-version }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [12, 14, 15, 16]

    steps:
      - name: checkout
        uses: actions/checkout@v2
        if: ${{ needs.changes.outputs.impactful == 'true' }}

      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        if: ${{ needs.changes.outputs.impactful == 'true' }}
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dependencies
        if: ${{ needs.changes.outputs.impactful == 'true' }}
        run: npm install

      - name: run build script
        if: ${{ needs.changes.outputs.impactful == 'true' }}
        run: npm run build

      - name: publish code coverage results
        uses: codecov/codecov-action@v2
        if: matrix.node-version == 16 && ${{ needs.changes.outputs.impactful == 'true' }}
        with:
          files: .coverage/unit/cobertura-coverage.xml
