name: macos-ci
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.impactful }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            impactful:
              - .github/workflows/mac.yml
              - generators/**/*
              - test/**/*
              - .eslint*
              - package*.json
              - ts*.json

  build:
    runs-on: macos-latest
    needs: detect-changes
    name: macos-node-v${{ matrix.node-version }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [12, 14, 15, 16]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: decide whether to skip this job
        if: ${{ needs.changes.outputs.impactful != 'true' }}
        run: echo "SKIP_JOB=1" >> "${GITHUB_ENV}"

      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dependencies
        run: npm install

      - name: run build script
        run: npm run build
